name: releases

on:
  workflow_run:
    workflows:
      - tests
    branches:
      - master
    types:
      - completed

jobs:
  try_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python (3.9)
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
      - name: Create release if new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/gh_release.py
